# Generated by Django 6.0.4 on 2026-04-16 22:11

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("gender_probability", models.FloatField()),
                ("sample_size", models.IntegerField()),
                ("age", models.IntegerField()),
                ("age_group", models.CharField(max_length=20)),
                ("country_id", models.CharField(max_length=5)),
                ("country_probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
