# Generated by Django 5.0.14 on 2026-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country_name",
            field=models.CharField(default="Nigeria", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE")], max_length=10
            ),
        ),
    ]
