# Generated by Django 5.0.14 on 2026-04-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_profile_country_name_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="sample_size",
        ),
    ]
